#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_dem_bones = env_modules.Clone()

env_dem_bones.Prepend(CPPPATH=["#core"])
env_dem_bones.Prepend(CPPPATH=["#scene"])
env_dem_bones.Prepend(CPPPATH=["#servers"])
env_dem_bones.Prepend(CPPPATH=["#editor"])
env_dem_bones.Prepend(CPPPATH=["thirdparty/eigen"])
env_dem_bones.Prepend(CPPPATH=["thirdparty/eigen/Eigen"])

# Suppress Eigen warnings that cause compilation failures
if env_dem_bones["CC"] == "gcc" or env_dem_bones["CC"] == "clang":
    env_dem_bones.Append(
        CCFLAGS=[
            "-Wno-enum-conversion",
            "-Wno-shadow",
            "-Wno-unused-result",
            "-Wno-sign-compare",
            "-Wno-maybe-uninitialized",
            "-Wno-alloc-size-larger-than",
        ]
    )

env_thirdparty = env_dem_bones.Clone()

# Only compile the minimal working files for now
env_dem_bones.add_source_files(env.modules_sources, "register_types.cpp")
env_dem_bones.add_source_files(env.modules_sources, "dem_bones_processor.cpp")
