#!/usr/bin/env python

Import("env")
Import("env_modules")

env_direct_delta_mush = env_modules.Clone()

# Add required include paths
env_direct_delta_mush.Append(CPPPATH=["#modules/direct_delta_mush"])

# Source files
sources = [
    "register_types.cpp",
    "direct_delta_mush.cpp",
    "ddm_mesh.cpp",
    "ddm_importer.cpp",
    "ddm_precomputer.cpp",
    "ddm_deformer.cpp",
]

# AMGCL is now used from Godot's main thirdparty directory

# Build the module
if env["target"] == "editor":
    env_direct_delta_mush.add_source_files(env.modules_sources, sources)
else:
    env_direct_delta_mush.add_source_files(env.modules_sources, sources)

# Note: Direct Delta Mush shaders are now compiled by the rendering server
# in servers/rendering/renderer_rd/shaders/SCsub
