#!/usr/bin/env python

Import("env")
Import("env_modules")

env_ies = env_modules.Clone()

thirdparty_dir = "#thirdparty/ies/"
env_ies.Prepend(CPPPATH=[thirdparty_dir])

# Godot source files

module_obj = []

env_ies.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
