#!/usr/bin/env python
from misc.utility.scons_hints import *
import os

Import("env")
Import("env_modules")

env_usd_import = env_modules.Clone()

# Link USD libraries from openusd module
env.Prepend(CPPEXTPATH=["#modules/openusd/thirdparty/install/include"])
env.Prepend(LIBPATH=["#modules/openusd/thirdparty/install/lib"])
env.Prepend(LIBS=[
    "libtbb.dylib",
    "libtbbmalloc.dylib",
    "libtbbmalloc_proxy.dylib",
    "libusd_usd.a",
    "libusd_usdGeom.a",
    "libusd_usdShade.a",
    "libusd_usdLux.a",
    "libusd_usdSkel.a",
    "libusd_usdUtils.a",
    "libusd_gf.a",
    "libusd_sdf.a",
    "libusd_tf.a",
    "libusd_vt.a",
    "libusd_ar.a",
    "libusd_kind.a",
    "libusd_pcp.a",
    "libusd_plug.a",
    "libusd_work.a",
    "libusd_arch.a",
    "libusd_garch.a",
    "libusd_hio.a",
    "libusd_ndr.a",
    "libusd_sdr.a",
    "libusd_trace.a"
])

# Godot source files
module_obj = []

env_usd_import.add_source_files(module_obj, "*.cpp")

if env.editor_build:
    env_usd_import.add_source_files(module_obj, "editor/*.cpp")

env.modules_sources += module_obj

