#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_duckdb = env_modules.Clone()

env_duckdb.Append(
    CPPPATH=[
        "thirdparty/duckdb",
    ]
)

env_duckdb.Append(
    CPPDEFINES=[
    ]
)

module_obj = []

env_duckdb.add_source_files(module_obj, "*.cpp")

thirdparty_obj = []
env_thirdparty = env_duckdb.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, "thirdparty/duckdb/*.cpp")
env.modules_sources += thirdparty_obj

if env_thirdparty.msvc:
    env_thirdparty.Append(CXXFLAGS=["/EHsc"])
else:
    env_thirdparty.Append(CCFLAGS=["-fexceptions"])

env.modules_sources += module_obj