#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_duckdb = env_modules.Clone()

env_duckdb.Append(
    CPPPATH=[
        "thirdparty/duckdb",
    ]
)

env_duckdb.Append(
    CPPDEFINES=[
    ]
)

module_obj = []

env_duckdb.add_source_files(module_obj, "*.cpp")
env_duckdb.add_source_files(module_obj, "thirdparty/duckdb/*.cpp")

if env.msvc:
    env.Append(CXXFLAGS=["/EHsc"])
else:
    env_duckdb.Append(CCFLAGS=["-fexceptions"])

env.modules_sources += module_obj
