#!/usr/bin/env python

from misc.utility.scons_hints import *

Import("env")

env_kusudama = env.Clone()
# Ensure module headers are found (staged migration may still include ewBIK headers)
env_kusudama.Prepend(CPPPATH=["#modules/kusudama"])
env_kusudama.Prepend(CPPPATH=["#modules/kusudama/src"])
env_kusudama.Prepend(CPPPATH=["#modules/kusudama/src/math"])

# Add sources from this module
env_kusudama.add_source_files(env.modules_sources, "src/*.cpp")
env_kusudama.add_source_files(env.modules_sources, "src/math/*.cpp")
env_kusudama.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_kusudama.add_source_files(env.modules_sources, "editor/*.cpp")
