#!/usr/bin/env python

Import('env')

# The main source files of our Slicer plugin. We could also
# do a Glob to get cpp files automatically but for now we'll
# use an opt-in process just to have better control over what goes
# into the final binary during development. (Especially because we
# have some test files mucking things up)
sources = [
    "register_types.cpp",
    "slicer.cpp",
    "sliced_mesh.cpp",
    "utils/slicer_face.cpp",
    "utils/intersector.cpp",
    "utils/triangulator.cpp"
]

module_env = env.Clone()

module_env.add_source_files(env.modules_sources, sources)
