#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_scene_optimize = env_modules.Clone()
env_scene_optimize.Prepend(CPPPATH=["#thirdparty/mesh_optimizer"])

# Temporarily disable xatlas compilation due to library issues
# env_scene_optimize.Prepend(CPPPATH=["#thirdparty/mesh_optimizer", "#modules/scene_merge/thirdparty/xatlas"])

env_thirdparty = env_scene_optimize.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, Glob("thirdparty/misc/*.cpp"))
env_thirdparty.add_source_files(env.modules_sources, Glob("#thirdparty/xatlas/*.cpp"))

# Godot's own source files
env_scene_optimize.add_source_files(env.modules_sources, "*.cpp")

# Editor plugin files (only when building editor)
if env.editor_build:
    env_scene_optimize.add_source_files(env.modules_sources, "merge_plugin.cpp")
